# Generated by Django 5.1.7 on 2025-03-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verificationcode'),
        ('users', '0003_verificationcode_user_phone'),
    ]

    operations = [
    ]
